### PR TITLE
fix: Revoke and pause chart

### LINKED ISSUE #93: Improving support for Paused and Revoked vesting contracts
### Intro
After the latest upgrades (See [https://github.com/decentraland/vestings-builder/pull/50](https://github.com/decentraland/vestings-builder/pull/50) and [https://github.com/decentraland/vestings-builder/pull/41](https://github.com/decentraland/vestings-builder/pull/41)) for the Vesting Contracts logic, the Vesting Dashboard lacks complete support for the Paused and Revoked status with periodic vesting schedules. 

This issue is about tackling multiple use cases regarding the previously mentioned use cases

### Revoked Contracts
Currently, when a Vesting contract is revoked, there is an error when calculating the total vesting amount. See for example [this Grant ](https://governance.decentraland.org/proposal/?id=a37682b0-7798-11ec-8188-4352ce3d30e7)asking for 30k and [it's vesting](https://vesting.decentraland.org/#/0x07b9fbb0b836f55dd4c19e79b1d673b3c83dcaaa) which got revoked at the 25k mark. In this case, the Total Vesting amount displays $25,084 when the value should be $30,000. In addition to this, the percentage of vested and released funds displays as 100% when the actual percentage should be 80.5%.

- [ ] Maintain the original Total Vesting amount when a contract is Revoked
- [ ] Calculate the % of Released and Vested Funds of the Total Vesting amount (The Released and Vested amounts will match since when a contract gets revoked, all the unreleased but vested funds get transferred to the beneficiary address)

Also, the projected vesting line keeps its upward trajectory when it should drop to 0 at the same timestamp that the Grant was revoked
See:
 
Screenshot 2023-08-29 at 13 34 57
(This screenshot is from a linear instead of a periodic vesting but the concept is the same)

It should be:

Screenshot 2023-08-29 at 13 45 23

- [ ] Grey vesting projection should drop to 0 when the contract gets revoked.
- [ ] If the Vesting Contract was Revoked, a banner should be displayed communicating the user that information.
Screenshot 2023-08-29 at 13 48 58

### Paused Contracts
Currently, when a Vesting gets paused, the projected vesting line keeps its upward trajectory when it should remain flat until the grant is either unpaused or revoked.
See:
Screenshot 2023-08-29 at 13 52 03

It should be:
Screenshot 2023-08-29 at 13 59 11
The Paused marker should use a yellow color instead of red

### Paused and then Revoked Contracts
When a Vesting gets paused, the behavior regarding the projected vesting line should be the same, and when the Vesting is revoked after the pause, the vesting line should drop to 0.

- [ ] When a Vesting is paused, the projected vesting line should remain flat until the Vesting gets either unpaused or Revoked
- [ ] When a Vesting gets Revoked after a pause, the projected vesting line drops to 0 and if there are any remaining funds to be released, the release line rises to the released amount.

Screenshot 2023-08-29 at 14 23 47

### Paused and then Unpaused Contracts
When a Vesting gets paused, the behavior regarding the projected vesting line should be the same, and when the Vesting is unpaused, the vesting lines (Projected and actual) should continue behaving the same as they were before the pause.

Screenshot 2023-08-29 at 14 08 20

- [ ] When a Vesting is paused, the projected vesting line should remain flat until the Vesting gets either unpaused or Revoked
- [ ] When a Vesting is unpaused, the projected and actual vesting lines keep its trajectory

### Periodic Vesting Contracts

- [ ] Copy should be updated from:

> Vesting is real-time and the beneficiary is able to release funds as they are vested. The beneficiary has released from said funds 0% of what is currently vested.

to:

> Vesting is periodic every 30 days and the beneficiary is able to release funds as they are vested. The beneficiary has released from said funds X% of what is currently vested.

### PR DESCRIPTION
**Pull request by ncomerci**
This closes #93

### CODE REVIEW

File: src/components/Dashboard/Chart/Chart.js [hunk 1]
```diff
@@ -221,9 +226,19 @@ function Chart(props) {
...
 
+  const isRevokedOrPaused = isRevoked || isPaused
+
   const responsive = useResponsive()
   const isMobile = responsive({ maxWidth: onlyMobileMaxWidth })
-  const toBeVestedLabel = t('chart.to_be_vested')
+  const tooltipDay = isRevoked || isPaused ? revokeOrPauseDay : daysFromStart
+  const getTodayMarkerColor = () => {
+    if (revoked) {
+      return 'var(--rovoked-color)'
```
Comment (andyesp) [inline src/components/Dashboard/Chart/Chart.js:236]: revoked

**Review by andyesp — CHANGES_REQUESTED** [review]

File: src/components/Dashboard/Chart/Chart.js [hunk 2]
```diff
@@ -132,8 +129,15 @@ function getReleaseData(start, cliff, releaseLogs, revokeLog) {
       )
     }
 
-    const [isRevoked, revokedDay] = getRevokedData(revokeLog, start)
-    const finalDataPoint = isRevoked ? revokedDay + 1 : today
+    const getFinalDataPoint = (isRevokedOrPaused) => {
+      if (isRevokedOrPaused) {
+        if (version === ContractVersion.V1) {
```
Comment (andyesp) [inline src/components/Dashboard/Chart/Chart.js:134]: both conditions can be in the same if

File: src/components/Dashboard/Chart/Chart.js [hunk 3]
```diff
@@ -132,8 +129,13 @@ function getReleaseData(start, cliff, releaseLogs, revokeLog) {
       )
     }
 
-    const [isRevoked, revokedDay] = getRevokedData(revokeLog, start)
-    const finalDataPoint = isRevoked ? revokedDay + 1 : today
+    const getFinalDataPoint = (isRevokedOrPaused) => {
```
Comment (andyesp) [inline src/components/Dashboard/Chart/Chart.js:132]: Is this function getting reused? You could write this like
```
const finalDataPoint = isRevokedOrPaused && version === ContractVersion.V1 ? revokeOrPauseDay + 1 : today
```

**Review by andyesp — APPROVED** [review]

**Review by 1emu — APPROVED** [review]
